/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author LENOVO
 */
public class FormKrs extends javax.swing.JFrame {
    controller.KrsController krsController = new controller.KrsController();
    controller.MahasiswaController mahasiswaController = new controller.MahasiswaController();
    controller.CourseController courseController = new controller.CourseController(); 
    controller.LecturerController lecturerController = new controller.LecturerController();
    
    int halamanSekarang = 1;
    int jumlahPerHalaman = 5;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormKrs.class.getName());

    /**
     * Creates new form FormKrs
     */
    
    private String hitungGradeHuruf(double sikap, double uts, double uas) {
    // 1. Hitung Nilai Akhir berdasarkan bobot
    double nilaiAkhir = (0.30 * sikap) + (0.35 * uts) + (0.35 * uas);
    
    // 2. Konversi ke Huruf
    if (nilaiAkhir >= 80) {
        return "A";
    } else if (nilaiAkhir >= 70) {
        return "B";
    } else if (nilaiAkhir >= 60) {
        return "C";
    } else if (nilaiAkhir >= 50) {
        return "D";
    } else {
        return "E";
    }
}
    
    public FormKrs() {
        initComponents();
        isiComboBox();
        loadData("");
    }
    
    private void isiComboBox() {
        jComboBoxMahasiswa.removeAllItems();
        jComboBoxCourse.removeAllItems();
        jComboBoxLecturer.removeAllItems();
        
        java.util.List<model.Mahasiswa> listMhs = mahasiswaController.getMahasiswa("", 1, 100);
        for (model.Mahasiswa mhs : listMhs) {
            // Tampilan visual: "NIM - Nama"
            jComboBoxMahasiswa.addItem(mhs.getNim() + " - " + mhs.getNamaMahasiswa());
        }
        
        java.util.List<model.Course> listCourse = courseController.getCourse("", 1, 100); // sesuaikan method get-mu
        for (model.Course c : listCourse) {
            // Tampilan visual: "Nama Matakuliah"
            jComboBoxCourse.addItem(c.getName());
        }
        
        java.util.List<model.Lecturer> listLecturer = lecturerController.getLecturer("", 1, 100);
        for (model.Lecturer lec : listLecturer) {
            jComboBoxLecturer.addItem(lec.getName());
        }
    }
 
    private void loadData(String keyword) {
        String[] column = { "ID", "NIM", "Nama Mahasiswa", "Mata Kuliah", "Dosen Pengajar", "Semester", "Grade"};
        javax.swing.table.DefaultTableModel modelTabel = new javax.swing.table.DefaultTableModel(column, 0);
        
        java.util.List<model.Krs> listKrs = krsController.getKrs(keyword, halamanSekarang, jumlahPerHalaman);
        
        for (model.Krs krs : listKrs) {
        String gradeHuruf = hitungGradeHuruf(krs.getNilaiSikap(), krs.getNilaiUts(), krs.getNilaiUas());

        Object[] baris = {
            krs.getIdKrs(),       
            krs.getNimMahasiswa(), 
            krs.getNamaMahasiswa(),  
            krs.getNamaCourse(),     
            krs.getNamaLecturer(),  
            krs.getSemester(),      
            gradeHuruf               
        };
        modelTabel.addRow(baris);
    }
        
        jTableKrs.setModel(modelTabel); 
        jTableKrs.getColumnModel().getColumn(0).setMinWidth(0);
        jTableKrs.getColumnModel().getColumn(0).setMaxWidth(0);
        jTableKrs.getColumnModel().getColumn(0).setPreferredWidth(0);
    
        jLabelHalaman.setText("Halaman " + halamanSekarang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxMahasiswa = new javax.swing.JComboBox<>();
        jComboBoxLecturer = new javax.swing.JComboBox<>();
        jComboBoxCourse = new javax.swing.JComboBox<>();
        jComboBoxSemester = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSikap = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextFieldUts = new javax.swing.JTextField();
        jTextFieldUas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKrs = new javax.swing.JTable();
        jButtonNext = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();
        jLabelHalaman = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("KRS ");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Krs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        jComboBoxMahasiswa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxMahasiswa.addActionListener(this::jComboBoxMahasiswaActionPerformed);

        jComboBoxLecturer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", " " }));

        jLabel2.setText("Mahasiswa:");

        jLabel3.setText("Mata Kuliah:");

        jLabel4.setText("Dosen Pengampu:");

        jLabel5.setText("Semester:");

        jTextFieldSikap.addActionListener(this::jTextFieldSikapActionPerformed);

        jLabel6.setText("Nilai");

        jButton3.setText("Tambah");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Edit");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Hapus");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jTextFieldUts.addActionListener(this::jTextFieldUtsActionPerformed);

        jTextFieldUas.addActionListener(this::jTextFieldUasActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxMahasiswa, 0, 245, Short.MAX_VALUE)
                            .addComponent(jComboBoxCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBoxSemester, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jComboBoxLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSikap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUts, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jComboBoxMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSikap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jTextFieldUts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jTableKrs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableKrs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableKrsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableKrs);

        jButtonNext.setText("Next>>");
        jButtonNext.addActionListener(this::jButtonNextActionPerformed);

        jButtonPrevious.setText("<<Previous");
        jButtonPrevious.addActionListener(this::jButtonPreviousActionPerformed);

        jLabelHalaman.setText("Halaman 1");

        jLabel7.setText("Cari Nama:");

        jTextFieldCari.addActionListener(this::jTextFieldCariActionPerformed);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jButtonPrevious)
                                .addGap(50, 50, 50)
                                .addComponent(jLabelHalaman)
                                .addGap(53, 53, 53)
                                .addComponent(jButtonNext))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton1)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHalaman, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jButtonPrevious)
                    .addComponent(jButtonNext))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMahasiswaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int indeksMhs = jComboBoxMahasiswa.getSelectedIndex();
        int indeksCourse = jComboBoxCourse.getSelectedIndex();
        int indeksLecturer = jComboBoxLecturer.getSelectedIndex();
    
    if (indeksMhs == -1 || indeksCourse == -1 || indeksLecturer == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pastikan semua data master sudah dipilih!");
        return;
    }
    
    if (jTextFieldSikap.getText().trim().isEmpty() || jTextFieldUts.getText().trim().isEmpty() || jTextFieldUas.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Nilai Sikap, UTS, dan UAS wajib diisi angka (isi 0 jika belum ada nilai)!");
        return;
    }
    
    try {
        double sikap = Double.parseDouble(jTextFieldSikap.getText().trim());
        double uts = Double.parseDouble(jTextFieldUts.getText().trim());
        double uas = Double.parseDouble(jTextFieldUas.getText().trim());
        
        java.util.List<model.Mahasiswa> listMhs = mahasiswaController.getMahasiswa("", 1, 100);
        java.util.List<model.Course> listCourse = courseController.getCourse("", 1, 100);
        java.util.List<model.Lecturer> listLecturer = lecturerController.getLecturer("", 1, 100);
        
        int idMahasiswaTerpilih = listMhs.get(indeksMhs).getId(); 
        int idCourseTerpilih = listCourse.get(indeksCourse).getId();       
        int idLecturerTerpilih = listLecturer.get(indeksLecturer).getId(); 
        int semesterTerpilih = Integer.parseInt(jComboBoxSemester.getSelectedItem().toString());
        
        model.Krs krsBaru = new model.Krs();
        krsBaru.setIdMahasiswa(idMahasiswaTerpilih);
        krsBaru.setIdCourse(idCourseTerpilih);
        krsBaru.setIdLecturer(idLecturerTerpilih);
        krsBaru.setSemester(semesterTerpilih);
        krsBaru.setNilaiSikap(sikap);
        krsBaru.setNilaiUts(uts);
        krsBaru.setNilaiUas(uas); 
        
        if (krsController.create(krsBaru) > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Transaksi KRS berhasil ditambahkan!");
            loadData(""); // Refresh JTable visual agar langsung menampilkan grade huruf baru
            
            jTextFieldSikap.setText("");
            jTextFieldUts.setText("");
            jTextFieldUas.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menambahkan transaksi KRS.");
        }
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Format nilai harus berupa angka yang valid!");
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTableKrsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKrsMouseClicked
        // TODO add your handling code here:
    int barisTerpilih = jTableKrs.getSelectedRow();
    
    if (barisTerpilih != -1) {
       
        String nimMhs = jTableKrs.getValueAt(barisTerpilih, 1).toString();
        String namaMhs = jTableKrs.getValueAt(barisTerpilih, 2).toString();
        String namaCourse = jTableKrs.getValueAt(barisTerpilih, 3).toString();
        String namaLecturer = jTableKrs.getValueAt(barisTerpilih, 4).toString();
        String semester = jTableKrs.getValueAt(barisTerpilih, 5).toString();
            
        String teksMahasiswa = nimMhs + " - " + namaMhs;
        
        jComboBoxMahasiswa.setSelectedItem(teksMahasiswa);
        jComboBoxCourse.setSelectedItem(namaCourse);
        jComboBoxLecturer.setSelectedItem(namaLecturer);
        jComboBoxSemester.setSelectedItem(semester);
    }
    }//GEN-LAST:event_jTableKrsMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here
    int barisTerpilih = jTableKrs.getSelectedRow();
    if (barisTerpilih == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih data yang ingin diubah pada tabel terlebih dahulu!");
        return;
    }
    
    double sikap = Double.parseDouble(jTextFieldSikap.getText().trim());
    double uts = Double.parseDouble(jTextFieldUts.getText().trim());
    double uas = Double.parseDouble(jTextFieldUas.getText().trim());

    int idKrsTerpilih = Integer.parseInt(jTableKrs.getValueAt(barisTerpilih, 0).toString());
    
    
    int indeksMhs = jComboBoxMahasiswa.getSelectedIndex();
    int indeksCourse = jComboBoxCourse.getSelectedIndex();
    int indeksLecturer = jComboBoxLecturer.getSelectedIndex();
   
    java.util.List<model.Mahasiswa> listMhs = mahasiswaController.getMahasiswa("", 1, 100);
    java.util.List<model.Course> listCourse = courseController.getCourse("", 1, 100);
    java.util.List<model.Lecturer> listLecturer = lecturerController.getLecturer("", 1, 100);
    
    int idMahasiswaTerpilih = listMhs.get(indeksMhs).getId();
    int idCourseTerpilih = listCourse.get(indeksCourse).getId();
    int idLecturerTerpilih = listLecturer.get(indeksLecturer).getId();
    int semesterTerpilih = Integer.parseInt(jComboBoxSemester.getSelectedItem().toString());
  
    model.Krs krsEdit = new model.Krs();
    krsEdit.setIdKrs(idKrsTerpilih); 
    
    krsEdit.setIdMahasiswa(idMahasiswaTerpilih);
    krsEdit.setIdCourse(idCourseTerpilih);
    krsEdit.setIdLecturer(idLecturerTerpilih);
    krsEdit.setSemester(semesterTerpilih);
    krsEdit.setNilaiSikap(sikap);
    krsEdit.setNilaiUts(uts);
    krsEdit.setNilaiUas(uas);
    
    // 6. Eksekusi ke controller
    if (krsController.update(krsEdit) > 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Data KRS berhasil diperbarui!");
        loadData(""); 
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal memperbarui data KRS.");
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
     
    int barisTerpilih = jTableKrs.getSelectedRow();
    if (barisTerpilih == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih data yang ingin dihapus pada tabel terlebih dahulu!");
        return;
    }
    
    
    int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin menghapus data transaksi KRS ini?", 
            "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
            
    if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
        
        int idKrsTerpilih = Integer.parseInt(jTableKrs.getValueAt(barisTerpilih, 0).toString());
        
        
        if (krsController.delete(idKrsTerpilih) > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data KRS berhasil dihapus!");
            loadData(""); 
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data KRS.");
        }
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextFieldSikapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSikapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSikapActionPerformed

    private void jTextFieldUtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUtsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUtsActionPerformed

    private void jTextFieldUasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUasActionPerformed

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
        // TODO add your handling code here:
        if (halamanSekarang > 1) {
        halamanSekarang--;
        loadData("");     
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Anda sudah berada di halaman pertama!");
    }
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed

    int jumlahBarisTabel = jTableKrs.getRowCount();
    
    if (jumlahBarisTabel < jumlahPerHalaman) {
        javax.swing.JOptionPane.showMessageDialog(this, "Anda sudah berada di halaman terakhir!");
        return;
    }
    
    // 2. Jika baris tabel masih penuh (sama dengan limit), ada kemungkinan halaman berikutnya masih ada data
    halamanSekarang++;
    loadData("");     
    
    
    if (jTableKrs.getRowCount() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Tidak ada data lagi di halaman berikutnya.");
        halamanSekarang--; 
        loadData("");      
    }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jTextFieldCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCariActionPerformed
        // TODO add your handling code here:
        String keyword = jTextFieldCari.getText().trim();
        halamanSekarang = 1; // Reset ke halaman 1 saat mulai mencari data
        loadData(keyword);
    }//GEN-LAST:event_jTextFieldCariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Buka kembali Form Dashboard
        FormDashboard dashboard = new FormDashboard();
        dashboard.setVisible(true);
        dashboard.setLocationRelativeTo(null);

        // Tutup form aktif saat ini
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormKrs().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JComboBox<String> jComboBoxCourse;
    private javax.swing.JComboBox<String> jComboBoxLecturer;
    private javax.swing.JComboBox<String> jComboBoxMahasiswa;
    private javax.swing.JComboBox<String> jComboBoxSemester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelHalaman;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKrs;
    private javax.swing.JTextField jTextFieldCari;
    private javax.swing.JTextField jTextFieldSikap;
    private javax.swing.JTextField jTextFieldUas;
    private javax.swing.JTextField jTextFieldUts;
    // End of variables declaration//GEN-END:variables
}
