/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LecturerController;
import javax.swing.JTable;
import model.Lecturer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author LENOVO
 */
public class FormLecturer extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormLecturer.class.getName());

    private controller.LecturerController lecController = new controller.LecturerController();
    private int halamanSekarang = 1;
    private final int jumlahPerHalaman = 5;
    private int idLecturerTerpilih = 0;
    
       /**
     * Creates new form FormLecturer
     */
    public FormLecturer() {
        initComponents();
        loadData("");
    }
public void loadData(String keyword){
String[] column = {"ID", "Nidn" , "Nama", "Expertise"};
javax.swing.table.DefaultTableModel modelTabel = new javax.swing.table.DefaultTableModel(column, 0);

java.util.List<model.Lecturer> listlec = lecController.getLecturer(keyword, halamanSekarang, jumlahPerHalaman);

for (model.Lecturer lec : listlec){
        Object[] row = {lec.getId(), lec.getNidn(), lec.getName(), lec.getExpertise()};
        modelTabel.addRow(row);
    }
    jTableLecturer.setModel(modelTabel);
    
    jLabelHalaman.setText("Halaman " + halamanSekarang);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNama = new javax.swing.JLabel();
        jLabelNidn = new javax.swing.JLabel();
        jLabelExpertise = new javax.swing.JLabel();
        jTextFieldNidn = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldExpertise = new javax.swing.JTextField();
        jButtonTambah = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLecturer = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCari = new javax.swing.JTextField();
        jButtonPrevious = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jLabelHalaman = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Data Lecturer"));

        jLabelNama.setText("Nama:");

        jLabelNidn.setText("Nidn:");

        jLabelExpertise.setText("Expertise:");

        jTextFieldNidn.setText("-");
        jTextFieldNidn.addActionListener(this::jTextFieldNidnActionPerformed);

        jTextFieldName.setText("-");
        jTextFieldName.addActionListener(this::jTextFieldNameActionPerformed);

        jTextFieldExpertise.setText("-");
        jTextFieldExpertise.addActionListener(this::jTextFieldExpertiseActionPerformed);

        jButtonTambah.setText("Tambah");
        jButtonTambah.addActionListener(this::jButtonTambahActionPerformed);

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(this::jButtonEditActionPerformed);

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(this::jButtonHapusActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonTambah)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEdit)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHapus))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNidn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jTextFieldNidn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jTextFieldName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelExpertise)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(jTextFieldExpertise, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNidn)
                    .addComponent(jTextFieldNidn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNama)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldExpertise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelExpertise))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTambah)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonHapus))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTableLecturer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableLecturer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLecturerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLecturer);

        jLabel4.setText("Cari Nama");

        jTextFieldCari.addActionListener(this::jTextFieldCariActionPerformed);

        jButtonPrevious.setText("<<Previous");
        jButtonPrevious.addActionListener(this::jButtonPreviousActionPerformed);

        jButtonNext.setText("Next>>");
        jButtonNext.addActionListener(this::jButtonNextActionPerformed);

        jLabelHalaman.setText("Halaman 1");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jButton1))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButtonPrevious)
                        .addGap(45, 45, 45)
                        .addComponent(jLabelHalaman)
                        .addGap(46, 46, 46)
                        .addComponent(jButtonNext)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButtonPrevious))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelHalaman)
                        .addComponent(jButtonNext)))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNidnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNidnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNidnActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldExpertiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldExpertiseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldExpertiseActionPerformed

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        // TODO add your handling code here:
    String nidn = jTextFieldNidn.getText().trim();
    String name = jTextFieldName.getText().trim();
    String expertise = jTextFieldExpertise.getText().trim();
    
    if (nidn.isEmpty() || name.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Nidn dan Nama tidak boleh kosong!");
        return;
    }
    model.Lecturer lecNew = new model.Lecturer(0, nidn, name, expertise);
 
    if(lecController.create(lecNew) > 0){
        javax.swing.JOptionPane.showMessageDialog(this, "Data Dosen berhasil ditambah");
        loadData("");
        
        jTextFieldNidn.setText("");
        jTextFieldName.setText("");
        jTextFieldExpertise.setText("");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menambah data.");
    }
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
    String nidn = jTextFieldNidn.getText().trim();
    String name = jTextFieldName.getText().trim();
    String expertise = jTextFieldExpertise.getText().trim();

    if (idLecturerTerpilih == 0 || nidn.isEmpty() || name.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih data pada tabel terlebih dahulu!");
        return;
        }
    model.Lecturer lecEdit = new model.Lecturer(idLecturerTerpilih, nidn, name, expertise);
    
    if (lecController.update(lecEdit) > 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Data Dosen Berhasil Diubah!");
        loadData(""); // Refresh tabel
        
        idLecturerTerpilih = 0;
        jTextFieldNidn.setEditable(true); 
        jTextFieldNidn.setText("");
        jTextFieldName.setText("");
        jTextFieldExpertise.setText("");  
    }else {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengubah data.");
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
    String nidn = jTextFieldNidn.getText().trim();

    if (nidn.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih data pada tabel yang ingin dihapus!");
        return;
    }
    
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus Nidn " + nidn + "?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
    if (confirm == javax.swing.JOptionPane.YES_OPTION){
        if (lecController.delete(nidn) > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data Dosen Berhasil Dihapus!");
            loadData(""); 
            jTextFieldNidn.setEditable(true);
            jTextFieldNidn.setText("");
            jTextFieldName.setText("");
            jTextFieldExpertise.setText("");     
        }
    }else {
        javax.swing.JOptionPane.showMessageDialog(this, "Data gagal dihapus!");
    }
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jTextFieldCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCariActionPerformed
        // TODO add your handling code here:
         String keyword = jTextFieldCari.getText().trim();
        halamanSekarang = 1; // Reset ke halaman 1 saat mulai mencari data
        loadData(keyword);
    }//GEN-LAST:event_jTextFieldCariActionPerformed

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
        // TODO add your handling code here:
    if (halamanSekarang > 1) {
    halamanSekarang--;
    loadData(jTextFieldCari.getText().trim());
    }
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
        if (jTableLecturer.getRowCount() == 5){
            halamanSekarang++;
            loadData(jTextFieldCari.getText().trim());
        }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jTableLecturerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLecturerMouseClicked
        // TODO add your handling code here:
int row = jTableLecturer.getSelectedRow();
if (row != -1) {
    idLecturerTerpilih = Integer.parseInt(jTableLecturer.getValueAt(row, 0).toString());
    
    jTextFieldNidn.setText(jTableLecturer.getValueAt(row, 1).toString());
    jTextFieldName.setText(jTableLecturer.getValueAt(row, 2).toString());
    jTextFieldExpertise.setText(jTableLecturer.getValueAt(row, 3).toString());
    jTextFieldNidn.setEditable(true);
}
    }//GEN-LAST:event_jTableLecturerMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Buka kembali Form Dashboard
        FormDashboard dashboard = new FormDashboard();
        dashboard.setVisible(true);
        dashboard.setLocationRelativeTo(null);

        // Tutup form aktif saat ini
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormLecturer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelExpertise;
    private javax.swing.JLabel jLabelHalaman;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelNidn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLecturer;
    private javax.swing.JTextField jTextFieldCari;
    private javax.swing.JTextField jTextFieldExpertise;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNidn;
    // End of variables declaration//GEN-END:variables
}
