/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CourseController;
import javax.swing.JTable;
import model.Course;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author LENOVO
 */
public class FormCourse extends javax.swing.JFrame {
    
    private controller.CourseController courseController = new controller.CourseController();    
    private int halamanSekarang = 1;
    private final int jumlahPerHalaman = 5;
    private int idCourseTerpilih = 0;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCourse.class.getName());
    /**
     * Creates new form FormCourse
     */
    public FormCourse() {
        initComponents();
        loadData("");
    }
 private void loadData(String keyword){
        String[] column = {"", "Code", "Matakuliah", "Sks"};
        javax.swing.table.DefaultTableModel modelTabel = new javax.swing.table.DefaultTableModel(column, 0);
        
        java.util.List<model.Course> listCourse = courseController.getCourse(keyword, halamanSekarang, jumlahPerHalaman);
        
        for (model.Course course : listCourse){
            Object[] row = {course.getId(), course.getCode(), course.getName(), course.getSks()};
            modelTabel.addRow(row);
        }
        jTableCourse.setModel(modelTabel);
        jLabelHalaman.setText("Halaman " + halamanSekarang);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCode = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jComboBoxSks = new javax.swing.JComboBox<>();
        jButtonTambah = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCourse = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCari = new javax.swing.JTextField();
        jButtonPrevious = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jLabelHalaman = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Course"));

        jLabel1.setText("Code:");

        jLabel2.setText("Matakuliah: ");

        jLabel3.setText("Sks:");

        jTextFieldCode.setText("-");

        jTextFieldName.setText("-");

        jComboBoxSks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", " " }));
        jComboBoxSks.addActionListener(this::jComboBoxSksActionPerformed);

        jButtonTambah.setText("Tambah");
        jButtonTambah.addActionListener(this::jButtonTambahActionPerformed);

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(this::jButtonEditActionPerformed);

        jButtonHapus.setText("Hapus");
        jButtonHapus.setToolTipText("");
        jButtonHapus.addActionListener(this::jButtonHapusActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxSks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addComponent(jTextFieldCode))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonTambah)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonHapus)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxSks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTambah)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonHapus))
                .addGap(33, 33, 33))
        );

        jTableCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCourseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCourse);

        jLabel4.setText("Cari Matakuliah:");

        jTextFieldCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCariKeyReleased(evt);
            }
        });

        jButtonPrevious.setText("<<Previous");
        jButtonPrevious.addActionListener(this::jButtonPreviousActionPerformed);

        jButtonNext.setText("Next >>");
        jButtonNext.addActionListener(this::jButtonNextActionPerformed);

        jLabelHalaman.setText("Halaman 1");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPrevious)
                .addGap(55, 55, 55)
                .addComponent(jLabelHalaman)
                .addGap(55, 55, 55)
                .addComponent(jButtonNext)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrevious)
                    .addComponent(jButtonNext)
                    .addComponent(jLabelHalaman))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
        if (jTableCourse.getRowCount() == 5) { 
        halamanSekarang++;
        loadData(jTextFieldCari.getText().trim());
        }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        // TODO add your handling code here:
    String code = jTextFieldCode.getText().trim();
    String name = jTextFieldName.getText().trim();
    int sks = Integer.parseInt(jComboBoxSks.getSelectedItem().toString());
    
    if (code.isEmpty() || name.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Code dan Nama Matakuliah tidak boleh kosong!");
        return;
    }
    model.Course courseNew = new model.Course(0, code, name, sks );
 
    if(courseController.create(courseNew) > 0){
        javax.swing.JOptionPane.showMessageDialog(this, "Data Matakuliah berhasil ditambah");
        loadData("");
        
        jTextFieldCode.setText("");
        jTextFieldName.setText("");
        jComboBoxSks.setSelectedIndex(0);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menambah data.");
        }
        
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
String code = jTextFieldCode.getText().trim();
String name = jTextFieldName.getText().trim();
int sks = Integer.parseInt(jComboBoxSks.getSelectedItem().toString());

if (idCourseTerpilih == 0 || code.isEmpty() || name.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Pilih data pada tabel terlebih dahulu!");
    return;
}

model.Course courseEdit = new model.Course(idCourseTerpilih, code, name, sks);
if (courseController.update(courseEdit) > 0) {
    javax.swing.JOptionPane.showMessageDialog(this, "Data matakuliah berhasil diubah!");
    loadData("");
    idCourseTerpilih = 0;
    jTextFieldCode.setText("");
    jTextFieldName.setText("");
    jComboBoxSks.setSelectedIndex(0);
} else {
    javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengubah data.");
}
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
    if (idCourseTerpilih == 0) {
    javax.swing.JOptionPane.showMessageDialog(this, "Pilih data pada tabel terlebih dahulu!");
    return;
}

int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Hapus matakuliah ini?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
if (confirm == javax.swing.JOptionPane.YES_OPTION) {
    if (courseController.delete(idCourseTerpilih) > 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Data matakuliah berhasil dihapus!");
        loadData("");
        idCourseTerpilih = 0;
        jTextFieldCode.setText("");
        jTextFieldName.setText("");
        jComboBoxSks.setSelectedIndex(0);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data.");
    }
}
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jTableCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCourseMouseClicked
        // TODO add your handling code here:
    int row = jTableCourse.getSelectedRow();
    if (row != -1) {
    idCourseTerpilih = Integer.parseInt(jTableCourse.getValueAt(row, 0).toString());
    jTextFieldCode.setText(jTableCourse.getValueAt(row, 1).toString());
    jTextFieldName.setText(jTableCourse.getValueAt(row, 2).toString());
    jComboBoxSks.setSelectedItem(jTableCourse.getValueAt(row, 3).toString());
}
    }//GEN-LAST:event_jTableCourseMouseClicked

    private void jComboBoxSksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSksActionPerformed

    private void jTextFieldCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCariKeyReleased
        // TODO add your handling code here:
        String keyword = jTextFieldCari.getText().trim();
        halamanSekarang = 1; // Reset ke halaman 1 saat mulai mencari data
        loadData(keyword);
    }//GEN-LAST:event_jTextFieldCariKeyReleased

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
        // TODO add your handling code here:
        if (halamanSekarang > 1) { 
        halamanSekarang--;
        loadData(jTextFieldCari.getText().trim());
        }
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FormDashboard dashboard = new FormDashboard();
        dashboard.setVisible(true);
        dashboard.setLocationRelativeTo(null);

        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCourse().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JComboBox<String> jComboBoxSks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelHalaman;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCourse;
    private javax.swing.JTextField jTextFieldCari;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
