/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.MahasiswaController;
import model.Mahasiswa;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class FormMahasiswa extends javax.swing.JFrame {
    private controller.MahasiswaController mhsController = new controller.MahasiswaController();
    private int halamanSekarang = 1;
    private final int jumlahPerHalaman = 5;
    private int idMahasiswaTerpilih = 0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMahasiswa.class.getName());

    /**
     * Creates new form FormMahasiswa
     */
    public FormMahasiswa() {
        initComponents();
        loadData("");
    }
private void loadData (String kataKunci){
    String[] kolom = {"ID", "NIM" , "Nama Mahasiswa", "Jurusan"};
    javax.swing.table.DefaultTableModel modelTabel = new javax.swing.table.DefaultTableModel(kolom, 0);
    
    // Memanggil via controller
    java.util.List<model.Mahasiswa> listMhs = mhsController.getMahasiswa(kataKunci, halamanSekarang, jumlahPerHalaman);
    
    for (model.Mahasiswa mhs : listMhs) {
        
        Object[] baris = {mhs.getId(), mhs.getNim(), mhs.getNamaMahasiswa(), mhs.getJurusan()};
        modelTabel.addRow(baris);
    }
    jTableMahasiswa.setModel(modelTabel);
    
    jLabelHalaman.setText("Halaman " + halamanSekarang);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextFieldCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMahasiswa = new javax.swing.JTable();
        jButtonPrevious = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNim = new javax.swing.JTextField();
        jComboBoxJurusan = new javax.swing.JComboBox<>();
        jButtonEdit = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jTextFieldNama = new javax.swing.JTextField();
        jButtonTambah = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jLabelHalaman = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Cari Nama: ");

        jTextFieldCari.addActionListener(this::jTextFieldCariActionPerformed);
        jTextFieldCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCariKeyReleased(evt);
            }
        });

        jTableMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMahasiswa);

        jButtonPrevious.setText("Previous");
        jButtonPrevious.addActionListener(this::jButtonPreviousActionPerformed);

        jLabel5.setText("Data Mahasiswa");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Data Mahasiswa"));

        jLabel1.setText("NIM:");

        jLabel2.setText("Nama:");

        jLabel3.setText("Jurusan:");

        jTextFieldNim.addActionListener(this::jTextFieldNimActionPerformed);

        jComboBoxJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ilmu Komputer", "Sistem Informasi", "TRPL" }));

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(this::jButtonEditActionPerformed);

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(this::jButtonHapusActionPerformed);

        jButtonTambah.setText("Tambah");
        jButtonTambah.addActionListener(this::jButtonTambahActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEdit)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHapus)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxJurusan, 0, 179, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNim))))
                        .addGap(55, 55, 55))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonHapus)
                    .addComponent(jButtonTambah))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jButtonNext.setText("Next");
        jButtonNext.addActionListener(this::jButtonNextActionPerformed);

        jLabelHalaman.setText("Halaman 1");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(jButtonPrevious)
                                .addGap(68, 68, 68)
                                .addComponent(jLabelHalaman)
                                .addGap(63, 63, 63)
                                .addComponent(jButtonNext))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel5)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrevious)
                    .addComponent(jButtonNext)
                    .addComponent(jLabelHalaman))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
         // TODO add your handling code here:                                            
    String nim = jTextFieldNim.getText().trim();
    String nama = jTextFieldNama.getText().trim();
    String jurusan = jComboBoxJurusan.getSelectedItem().toString();
    
    if (nim.isEmpty() || nama.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "NIM dan Nama tidak boleh kosong!");
        return;
    }
    model.Mahasiswa mhsBaru = new model.Mahasiswa(0, nim, nama, jurusan);
    
    // GANTI DI SINI: menggunakan mhsController.create
    if (mhsController.create(mhsBaru) > 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Data Mahasiswa berhasil ditambah");
        loadData("");
        
        jTextFieldNim.setText("");
        jTextFieldNama.setText("");
        jComboBoxJurusan.setSelectedIndex(0);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal menambah data.");
    }
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jTextFieldNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNimActionPerformed

    private void jTableMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMahasiswaMouseClicked
        // TODO add your handling code here:
int row = jTableMahasiswa.getSelectedRow();
    if (row != -1) {
        
        idMahasiswaTerpilih = Integer.parseInt(jTableMahasiswa.getValueAt(row, 0).toString());
       
        jTextFieldNim.setText(jTableMahasiswa.getValueAt(row, 1).toString());
        jTextFieldNama.setText(jTableMahasiswa.getValueAt(row, 2).toString());
        jComboBoxJurusan.setSelectedItem(jTableMahasiswa.getValueAt(row, 3).toString());
    }
    }//GEN-LAST:event_jTableMahasiswaMouseClicked

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:                                          
    String nim = jTextFieldNim.getText().trim();
    String nama = jTextFieldNama.getText().trim();
    String jurusan = jComboBoxJurusan.getSelectedItem().toString();

    if (nim.isEmpty() || nama.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih data pada tabel terlebih dahulu!");
        return;
    }

    model.Mahasiswa mhsEdit = new model.Mahasiswa(idMahasiswaTerpilih, nim, nama, jurusan);
   
    if (mhsController.update(mhsEdit) > 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Data Mahasiswa Berhasil Diubah!");
        loadData(""); // Refresh tabel
        jTextFieldNim.setEditable(true); 
        jTextFieldNim.setText("");
        jTextFieldNama.setText("");
        jComboBoxJurusan.setSelectedIndex(0);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengubah data.");
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:                                           
    String nim = jTextFieldNim.getText().trim();

    if (nim.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih data pada tabel yang ingin dihapus!");
        return;
    }

    int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus NIM " + nim + "?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
    if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
        
        
        if (mhsController.delete(idMahasiswaTerpilih) > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data Mahasiswa Berhasil Dihapus!");
            loadData(""); 
            jTextFieldNim.setEditable(true);
            jTextFieldNim.setText("");
            jTextFieldNama.setText("");
            jComboBoxJurusan.setSelectedIndex(0);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data.");
        }
    }

    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jTextFieldCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCariActionPerformed

    private void jTextFieldCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCariKeyReleased
        // TODO add your handling code here:
        String kataKunci = jTextFieldCari.getText().trim();
        halamanSekarang = 1; // Reset ke halaman 1 saat mulai mencari data
        loadData(kataKunci);
    }//GEN-LAST:event_jTextFieldCariKeyReleased

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
        // TODO add your handling code here:
    if (halamanSekarang > 1) {
        halamanSekarang--;
        loadData(jTextFieldCari.getText().trim());
}
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
    if (jTableMahasiswa.getRowCount() == 5) { 
        halamanSekarang++;
        loadData(jTextFieldCari.getText().trim());
}
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    FormDashboard dashboard = new FormDashboard();
    dashboard.setVisible(true);
    dashboard.setLocationRelativeTo(null);
    
    this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMahasiswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JComboBox<String> jComboBoxJurusan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelHalaman;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMahasiswa;
    private javax.swing.JTextField jTextFieldCari;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldNim;
    // End of variables declaration//GEN-END:variables
}
