/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author LENOVO
 */
public class FormDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormDashboard.class.getName());

    /**
     * Creates new formDahsboard
     */
    public FormDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCourse = new javax.swing.JLabel();
        jLabelKrs = new javax.swing.JLabel();
        jLabelMahasiswa = new javax.swing.JLabel();
        jLabelLecturer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jToggleButtonLogout = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(183, 245, 245));

        jLabelCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Book.png"))); // NOI18N
        jLabelCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCourseMouseClicked(evt);
            }
        });

        jLabelKrs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Info1.png"))); // NOI18N
        jLabelKrs.setText("jLabel4");
        jLabelKrs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelKrsMouseClicked(evt);
            }
        });

        jLabelMahasiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Person.png"))); // NOI18N
        jLabelMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMahasiswaMouseClicked(evt);
            }
        });

        jLabelLecturer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Teacher.png"))); // NOI18N
        jLabelLecturer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLecturerMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("COURSE");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("KRS");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("LECTURER");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("STUDENT");

        jToggleButtonLogout.setText("LOGOUT");
        jToggleButtonLogout.addActionListener(this::jToggleButtonLogoutActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jLabelCourse)
                    .addComponent(jLabelKrs, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(147, 147, 147)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelMahasiswa)
                    .addComponent(jLabelLecturer)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButtonLogout)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButtonLogout)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelKrs)
                    .addComponent(jLabelMahasiswa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelLecturer)
                    .addComponent(jLabelCourse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMahasiswaMouseClicked
        // TODO add your handling code here:
     FormMahasiswa mhsForm = new FormMahasiswa();
    mhsForm.setVisible(true);
    mhsForm.setLocationRelativeTo(null); // Muncul di tengah layar
    
    this.dispose();
    }//GEN-LAST:event_jLabelMahasiswaMouseClicked

    private void jLabelKrsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelKrsMouseClicked
        // TODO add your handling code here:
    FormKrs krsForm = new FormKrs();
    krsForm.setVisible(true);
    krsForm.setLocationRelativeTo(null);
    
    
    this.dispose();
    }//GEN-LAST:event_jLabelKrsMouseClicked

    private void jLabelCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCourseMouseClicked
        // TODO add your handling code here:
         FormCourse courseForm = new FormCourse();
    courseForm.setVisible(true);
    courseForm.setLocationRelativeTo(null);
    
   
    this.dispose();
    }//GEN-LAST:event_jLabelCourseMouseClicked

    private void jLabelLecturerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLecturerMouseClicked
        // TODO add your handling code here:
        FormLecturer lecturerForm = new FormLecturer();
    lecturerForm.setVisible(true);
    lecturerForm.setLocationRelativeTo(null); 
    
    // 2. Tutup Dashboard yang sedang aktif
    this.dispose();
    }//GEN-LAST:event_jLabelLecturerMouseClicked

    private void jToggleButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonLogoutActionPerformed
        // TODO add your handling code here:
        FormLogin loginForm = new FormLogin();
    loginForm.setVisible(true);
    loginForm.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_jToggleButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCourse;
    private javax.swing.JLabel jLabelKrs;
    private javax.swing.JLabel jLabelLecturer;
    private javax.swing.JLabel jLabelMahasiswa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButtonLogout;
    // End of variables declaration//GEN-END:variables
}
